{
 "title": "Certificates",
 "description": "A Grafana Dashboard for visualizing the data collected by the x509_cert Telegraf plugin for InfluxDB.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "x509_cert", "label": "x509_cert datasource", "query": "influxdb" },
   {
    "name": "zone",
    "query": "SHOW TAG VALUES ON \"ssl_certs_info\" WITH KEY = \"zone\""
   },
   {
    "name": "environment",
    "query": "SHOW TAG VALUES ON \"ssl_certs_info\" WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "Invalid certificates",
   "type": "table",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "serial_number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "x509_cert",
     "query": "SELECT \"startdate\"  * 1000, \"enddate\"  * 1000, \"expiry\", \"verification_error\", \"verification_code\" FROM \"x509_cert\" WHERE (\"environment\" =~ /^$environment$/ AND \"zone\" =~ /^$zone$/ AND \"verification\" = 'invalid') AND $timeFilter GROUP BY \"source\", \"serial_number\" LIMIT 1",
     "select": [
      [
       { "params": [ "startdate" ], "type": "field" },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "enddate" ], "type": "field" },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "expiry" ], "type": "field" }
      ],
      [
       { "params": [ "verification_error" ], "type": "field" }
      ],
      [
       { "params": [ "verification_code" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "zone", "operator": "=~", "value": "/^$zone$/" },
      { "condition": "AND", "key": "verification", "operator": "=", "value": "invalid" }
     ]
    }
   ]
  },
  {
   "title": "Certificate  expiration list",
   "type": "table",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "serial_number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "x509_cert",
     "query": "SELECT \"startdate\" * 1000, \"enddate\"  * 1000, \"expiry\", \"verification_error\", \"verification_code\" FROM \"x509_cert\" WHERE (\"environment\" =~ /^$environment$/ AND \"zone\" =~ /^$zone$/) AND $timeFilter GROUP BY \"source\", \"serial_number\" LIMIT 1",
     "select": [
      [
       { "params": [ "startdate" ], "type": "field" },
       { "params": [ "* 1000" ], "type": "math" }
      ],
      [
       { "params": [ "enddate" ], "type": "field" },
       { "params": [ " * 1000" ], "type": "math" }
      ],
      [
       { "params": [ "expiry" ], "type": "field" }
      ],
      [
       { "params": [ "verification_error" ], "type": "field" }
      ],
      [
       { "params": [ "verification_code" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "zone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  },
  {
   "title": "Certificate  details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "common_name" ], "type": "tag" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "issuer_common_name" ], "type": "tag" },
      { "params": [ "locality" ], "type": "tag" },
      { "params": [ "organization" ], "type": "tag" },
      { "params": [ "organizational_unit" ], "type": "tag" },
      { "params": [ "province" ], "type": "tag" },
      { "params": [ "public_key_algorithm" ], "type": "tag" },
      { "params": [ "signature_algorithm" ], "type": "tag" },
      { "params": [ "serial_number" ], "type": "tag" },
      { "params": [ "san" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "x509_cert",
     "query": "SELECT \"expiry\" FROM \"x509_cert\" WHERE (\"environment\" =~ /^$environment$/ AND \"zone\" =~ /^$zone$/) AND $timeFilter GROUP BY \"source\", \"common_name\", \"country\", \"issuer_common_name\", \"locality\", \"organization\", \"organizational_unit\", \"province\", \"public_key_algorithm\", \"signature_algorithm\", \"serial_number\", \"san\" LIMIT 1",
     "select": [
      [
       { "params": [ "expiry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "zone", "operator": "=~", "value": "/^$zone$/" }
     ]
    }
   ]
  }
 ]
}